### ISSUE TITLE
[Back] HU13 - T13.04 - Listar Cadenas de hotel

### ISSUE THREAD

**Issue by jolomoreno** [mdw-agiles/pr-mdw-agiles-back#4]
- Tarea 4 -  [BACK] Habilitar endpoint para devolver listado de cadenas de hotel. (GET /chains)

- Tiempo dedicado: 5h

**Comment by alexph9** [comment]
Done!

**Comment by alexph9** [comment]
We should add the id in HotelChainDTO

**Comment by alexph9** [comment]
Done!
