### ISSUE TITLE
[Back] HU13 - T13.06 - Listar Habitaciones

### ISSUE THREAD

**Issue by jolomoreno** [mdw-agiles/pr-mdw-agiles-back#6]
- Tarea 6 -  [BACK] Habilitar endpoint para devolver listado de habitaciones de un hotel de una cadena de hoteles. ~~(GET /habitaciones?hotel=X)~~ (GET /room/search?hotelName=X)

- Tiempo dedicado: 4h

**Comment by dpb-upm** [comment]
Se olvidó añadir test del repositorio, después de cerrar el ticket. Se ha añadido a la rama para tener en la misma rama todo el código relacionado en lugar de crear un nuevo ticket.
